package com.cn.dao;

import com.cn.model.SmsPush;
import com.cn.model.SmsPushExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsPushMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_push
     *
     * @mbggenerated
     */
    int countByExample(SmsPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_push
     *
     * @mbggenerated
     */
    int deleteByExample(SmsPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_push
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_push
     *
     * @mbggenerated
     */
    int insert(SmsPush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_push
     *
     * @mbggenerated
     */
    int insertSelective(SmsPush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_push
     *
     * @mbggenerated
     */
    List<SmsPush> selectByExample(SmsPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_push
     *
     * @mbggenerated
     */
    SmsPush selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_push
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmsPush record, @Param("example") SmsPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_push
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmsPush record, @Param("example") SmsPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_push
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmsPush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_push
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmsPush record);
}