package com.cn.dao;

import com.cn.model.TaskData;
import com.cn.model.TaskDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_data
     *
     * @mbggenerated
     */
    int countByExample(TaskDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_data
     *
     * @mbggenerated
     */
    int deleteByExample(TaskDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_data
     *
     * @mbggenerated
     */
    int insert(TaskData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_data
     *
     * @mbggenerated
     */
    int insertSelective(TaskData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_data
     *
     * @mbggenerated
     */
    List<TaskData> selectByExample(TaskDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_data
     *
     * @mbggenerated
     */
    TaskData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_data
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TaskData record, @Param("example") TaskDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_data
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TaskData record, @Param("example") TaskDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaskData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaskData record);
}